### ISSUE TITLE
Full namespacing and explicit init()

### ISSUE THREAD

**Issue by mrclay** [mikecao/flight#2]
Nice work on this framework. In particular I like that it does not alter global state by auto-starting a session or ini_set()-ing values, because this allows embedding into existing apps with their own session. Just a couple things bug me:
1. IMO all class names should be namespaced, particularly names as common as "Request", "View", etc. You could prepend "Flight_" to these names or placing them under a real "Flight" namespace. This would also help bring the framework in line with the PSR0 autoloading standard.
2. I think it's poor form for class files (like Flight.php) to automatically execute code (init()). Having the user call the init would not be unreasonable. In general I'd have autoloading setup so calling Flight::init() would load the class file anyway.

Anyway, just some opinions. Have a good one.

**Comment by mikecao** [comment]
1. I agree. I'm currently working on namespacing all the default components.
2. I don't really have a problem with the init() since the Flight class can't be instantiated. You're really running the framework once you've included the file. But still it might be possible to simply move all the init() code to start() instead. I'll have to look into it.

Thanks for your comments.
