### ISSUE TITLE
PSR-0, composer and next release

### ISSUE THREAD

**Issue by ghost** [mikecao/flight#41]
Hi
Well this is not really an issue per se, but a "nice to have".

I was checking packagist (composer.json) for flight and saw that there was a master-dev version, but no release versions, even though I believe there is a release v0.1 and v0.2?

It would be nice to have a "stable" version on packagist even though it is only a beta, but master-dev isn't really stable at all. Could I encourage you to do a v0.3 release and put it on packagist?

Also I noticed that the autoloading on packagist was "files". That got me thinking, since flight is namespaced, it would require very few steps to make it PSR-0 compliant.

1) remove the includes from Flight.php
2) namespace Flight.php to flight
3) put the files into a folder 'flight'
_edit_
4) Exceptions in Flight.php should be namespaced '\'
_edit_

Then for the packagist release, put something like (or whatever you prefer):
"autoload": {
    "psr-0": {"flight\": "/src"}
}

In examples and source files, it is easy to use flight as always, it just requires one extra line: 

use flight\Flight;
Flight::map('blabla', ...)

PS: Thanks for a really great micro-php framework

/Thomas

**Comment by lucasrubini** [comment]
+1

**Comment by mikecao** [comment]
I'm currently working on being better at versioning, so I'll try to make the updates for the next release.

However I'm wary of putting the main Flight class in a namespace because it loses a lot of simplicity. Users would have to remember to the `use` statement everywhere in their application. I'm tinkering with some ideas about splitting the main functionality into a separate, namespace application instance and keep Flight as a static global. Then users who are more comfortable with namespaces can use the alternative. Hopefully that will provide the best of both worlds.

**Comment by kafene** [comment]
I think Flight's main class being global is a good enough way of handling things - it is not a class that one would want multiple instances of, and it's basically a static facade to the rest of the framework.

I think you could avoid the necessity of the `use` statement by calling `class_alias()` after `Flight::init()` at the end of the main file.
