### ISSUE TITLE
 single layout template not works

### ISSUE THREAD

**Issue by samuelmesq** [mikecao/flight#7]
single layout template not works, content is added **before** body close tag, it is not where I put

**Comment by mikecao** [comment]
Can you post more information about your template setup? Maybe an example of what you're doing.

**Comment by samuelmesq** [comment]
for example:

**# index.php**

<?php

require 'flight/Flight.php';

Flight::render('layout');

Flight::route('/about', function(){
    Flight::render('about','content');
});

?>

**# layout.php**
<code>
<html>
<head><title>my project</title></head>
<body>
    <div id="main"><?php echo $content ?></div>
        <footer>my footer</footer>
</body>
</html>
</code>

in this case, the contents of "views/about.php" is added after the footer tag

**UPDATE**

I tested in Internet Explorer and the html code result is :

<code>
</body>
</html><p>content</p>
</code>

**Comment by mikecao** [comment]
That's because you're calling the Flight::render method outside of a route. So it will always render the layout first, then when it matches a route, like /about, it will render that content. The correct way would be to render the content first, then the layout. This is explained further in the Layouts section of the README file.
