### ISSUE TITLE
\Flight\Loader::loadClass doesn't throw exception

### ISSUE THREAD

**Issue by Awnage** [mikecao/flight#82]
I get a PHP Fatal error when I try to load a class that has not been registered yet

``` php
$a=Flight::b();
```

However, \Flight\Loader::loadClass's phpdoc says

```
     * @throws \Exception If class not found
```

Did I miss something? Any thought to adding a ::registered() boolean?

**Comment by mikecao** [comment]
Sorry, that's a mistake in the docs. The exception throwing has been removed because it interferes with the `class_exists` function. You should use class_exists if you want to check if your class has been loaded. A ::registered method won't help because you can register an non-existent class and it will still throw an error.
